### ISSUE TITLE
Unable to find tag 2.0.0-beta.27

### ISSUE THREAD

**Issue by SevenworksDev** [geode-sdk/build-geode-mod#10]
Trying to use GitHub Codespaces along with build-geode-mod to avoid having to install 6gb worth of useless stuff just to build a mod on windows and also build it faster. It trys to detect the geode version from mod.json and ig its not finding something it needs based off that.

Logs: https://pastebin.com/raw/G6d2wJ33

mod.json:
```json
{
	"geode": "2.0.0-beta.27",
	"gd": "2.204",
	"version": "v1.0.0",
	"id": "sevenworks.womp-geode",
	"name": "womp womp",
	"developer": "Sevenworks",
	"description": "plays funny sound"
}
```

**Comment by matcool** [comment]
fixed on later cli, it expects the v prefix
