### ISSUE TITLE
.hpp file error

### ISSUE THREAD

**Issue by entity12208** [geode-sdk/build-geode-mod#17]
Whenever i use the script as an action, it says some error about the playerobject.hpp file not being found. How do I fix this?

**Comment by entity12208** [comment]
Here's the exact error:
D:/a/BetterEditorCollabX/BetterEditorCollabX/src/BetterEditorCollab.cpp:1:10: fatal error: 'Geode/modify/LevelEditorLayer.hpp' file not found

    1 | #include <Geode/modify/LevelEditorLayer.hpp>

      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

1 error generated.

ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

**Comment by entity12208** [comment]
Here's my code:

name: Geode

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: 'latest'
          cli: 'latest'
          configure-args: ''
          build-args: ''
          build-config: 'release'
          export-pdb: ''
          path: ''
          combine: 'false'
          target: 'Win64'
          bindings: ''
          bindings-ref: ''
          android-min-sdk: ''
          use-lto: 'true'

**Comment by FireMario211** [comment]
why do you need to set all of those options
